# Generated by Django 5.0.6 on 2024-05-31 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_reciperequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuinventoryitem',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
