# Generated by Django 5.0.4 on 2024-05-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
